import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BMC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="ml-3 bg-onboard text-[50px] text-cyan-400">
        <div className="ml-3 bg-onboard-overlay text-[50px] text-cyan-400"></div>
      </div>
    </div>
  );
}
