import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>BMC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-onboard font-bold text-[100px] text-white flex flex-grow flex-col justify-center items-center text-center">
        <p>Decentralized crowd funding platform</p>
        <img className="brand-logo" src="/logo.svg" />
      </div>
    </>
  );
}
